<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
    <FileVersion>2.2.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <OutputType>Library</OutputType>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetZip.Original" Version="2025.1.26" />
    <PackageReference Include="Joveler.Compression.ZLib" Version="4.1.0" />
    <PackageReference Include="K4os.Compression.LZ4" Version="1.2.16" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2-beta1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    <PackageReference Include="System.Resources.Extensions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utils\IconExtractor\" />
  </ItemGroup>



</Project>
